item:
  material: 'DIAMOND_HOE'
  name: '&3Harvester Hoe'
  lore:
    - '&eGets all the sugarcane from the block you hit to the highest'
    - '&ethan automatically sells it'
    - '&bPurchasable @ &7store.example.com'

permission: 'harvesterhoe.admin'
sugarcane-price: 20



