item:
  material: 'DIAMOND_HOE'
  name: '§c§lHarvester Hoe'
  lore:
    - '§ePuts sugancane directly into your inventory'
    - '§eGets all the sugarcane from the block you hit to the highest'

permission: 'harvesterhoe.use'



